User.create(email: "azhir@master.com",password: "123456",role:"sys_master")
User.create(email: "azhir@admin.com",password: "123456",role:"sys_admin")
User.create(email: "azhir@expert.com",password: "123456",role:"sys_expert")
User.create(email: "azhir@cafe_ower.com",password: "123456",role:"cafe_ower")
User.create(email: "azhir@player.com",password: "123456",role:"player")
