User.create(email: "azhir@master.com",password: "123456",role:"sys_master")
User.create(email: "azhir@admin.com",password: "123456",role:"sys_admin")
User.create(email: "azhir@expert.com",password: "123456",role:"sys_expert")
User.create(email: "azhir@coffee_owner.com",password: "123456",role:"coffee_owner")
User.create(email: "azhir@player.com",password: "123456",role:"player")
